### ISSUE TITLE
Thanks for your job! Great!

### ISSUE THREAD

**Issue by gbrault** [TomNicholas/coronavirus#1]
Just to let you know 

- that it requires scipy 1.4.1 at least, else, solving fail (I had 1.3.2 and got the issue)
- you should correct the binder link with someting like https://mybinder.org/v2/gh/TomNicholas/coronavirus/master

**Comment by TomNicholas** [comment]
Thanks!

I've updated the binder link.

The scipy 1.4.1 requirement is already in the readme and in the environment.yml file so it should load the correct version automatically on binder.
